### ISSUE TITLE
TypeError: Cannot read property 'published' of null

### ISSUE THREAD

**Issue by ghost** [ThePatches/Goodloe#4]
I'm receiving error:

```
sudo nodejs server.js 

{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
{ suggest: [Function: suggestFeature], requestUser: [Function: reqUser] }
opened database

/goodloe/server.js:76
    if (member.published == false) // broadcast stuff goes here
          ^
TypeError: Cannot read property 'published' of null
    at Promise.<anonymous> (/goodloe/server.js:76:15)
    at Promise.<anonymous> (/goodloe/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
at Promise.EventEmitter.emit (events.js:95:17)
at Promise.emit (/goodloe/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
at Promise.fulfill (/goodloe/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)
at Promise.resolve (/goodloe/node_modules/mongoose/lib/promise.js:114:23)
at Promise.<anonymous> (/goodloe/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
at Promise.EventEmitter.emit (events.js:95:17)
at Promise.emit (/goodloe/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
at Promise.fulfill (/goodloe/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)
```

Working through it now. Will update issue if I find anything.

**Comment by ghost** [comment]
```
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
```

Resolved by the following: http://stackoverflow.com/questions/21656420/failed-to-load-c-bson-extension

Edit 'node_modules/mongoose/node_modules/mongodb/node_modules/bson/ext/index.js'

Change:
        bson = require('../build/Release/bson');

To
        bson = require('bson');

**Comment by ghost** [comment]
Okay commenting out:

```
//if (member.published == false) // broadcast stuff goes here
//{
//    member.published = true;
//    member.save();
//}
//app.set('version', member.version);
```

Gets me up and running. Will revisit these null issues shortly.
